name: Lint
on:
  pull_request:
    paths:
      - '**.py'
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check with ruff
        uses: chartboost/ruff-action@v1
      - name: Check with pyright
        uses: jakebailey/pyright-action@v1
      - name: Check with isort
        uses: isort/isort-action@master
